version: '3'

services:
  zookeeper:
    container_name: zookeper
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
#    volumes:
#      - ~/eng-micro-platform/zoodata:/var/lib/zookeeper/data
#      - ~/eng-micro-platform/zoolog:/var/lib/zookeeper/log
  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    tty: true
    stdin_open: true
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
#    volumes:
#      - ~/eng-micro-platform/kafkadata:/var/lib/kafka/data
    depends_on:
      - zookeeper
